# Generated by Django 2.2.4 on 2019-08-19 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='matches',
            new_name='matchez',
        ),
    ]
